name: CI Build

on:
  push:
    paths:
       - 'README.md'
       - '**.go'
       - 'go.mod'
       - 'go.sum'
       - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24' ]
    steps:
      - name: Set up Go v${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          go version
          go mod download && go mod verify

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vet code
        run: go vet ./...

      - name: Build
        run: go build -v .
