name: CI Check PR

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24.2' ]
    steps:
      - name: Set up Go v${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          go version
          go mod download && go mod verify

      - name: Cache modules
        uses: actions/cache@v3
        with:
          path: $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go

      - name: Vet code
        run: go vet

      - name: Sample Build
        run: go build -v .
